name: My First Workflow

on: 
  workflow_dispatch:
    inputs:
      loglevel:
        description: 'log level'
        required: true
        default: 'warning'
        type: choice
        options:
          - info
          - warning

jobs:
    first_job:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repo
              uses: actions/checkout@v4

            - name: List
              run: ls -al
              
            - name: execute shell script
              run: |
                chmod +x ascii-script.sh
                ./ascii-script.sh
